🧹 Remove Storybook
calibreapp/react-live-chat-loader pull request #181
Opened 2022-10-05 05:16 UTC by robmorieson

## What does this PR introduce?

Removes Storybook and all its deps in favour of highlighting the enclosing example website (`/website`) to preview the current list of supported providers

2022-10-05 06:52 UTC, benschwarz approved these changes
LGTM!

2022-10-05 07:06 UTC, thefoxis requested changes

2022-10-05 07:06 UTC, thefoxis commented on README.md
> +For initial setup of the example app, be sure to first run `npm install` + `npm run build` in the root level of the repository, before running `npm install` in the `website` directory.
```suggestion
For the initial setup of the example app, be sure first to run `npm install` + `npm run build` in the root level of the repository before running `npm install` in the `website` directory.
```

2022-10-05 07:06 UTC, thefoxis commented on README.md
> +The following scripts in example app will then be available:
```suggestion
The following scripts in the example app will then be available:
```

2022-10-05 07:06 UTC, thefoxis commented on README.md
> +> 📝  Note that some providers require whitelisted publicly accessible domains served over HTTPS — a service like [ngrok](https://ngrok.com/) can be helpful in achieving this locally
```suggestion
> 📝  Note that some providers require safe-listed, publicly accessible domains served over HTTPS — a service like [ngrok](https://ngrok.com/) can can help achieve this locally.
```

2022-10-06 04:09 UTC, thefoxis approved these changes

2022-10-06 04:09 UTC, merged