Amarnath/fix intercom position
calibreapp/react-live-chat-loader pull request #318
Opened 2023-09-06 13:46 UTC by amarnath-cohesive

👋🏻 Hi there! 

This template will help you describe the work you’ve done, so one of the project maintainers can review and potentially accept it promptly. Please fill relevant sections below and feel free to delete what does not apply to your work (including this comment).

Thank you for helping us improve React Live Chat Loader! ⚡️

***

## What does this PR introduce?
In a few bullet points, please describe the changes this Pull Request makes. e.g.:

- fixes #260 .
- adds a style prop to the intercom widget which will allow setting the `left` and `right` CSS props by the user.

2023-10-01 22:56 UTC, benschwarz commented
Hi @amarnath-cohesive, could you please add a description of the changes you've made and why?

2023-10-12 23:33 UTC, robmorieson requested changes
@amarnath-cohesive thanks for your contribution!  This approach of being able to customise the placeholder icon styles for Intercom is an ideal solution to #260 as the issue is inconsistent so we don't want to change the default styles for everyone. 

I've left a couple of pointers in the code review.  

It might also be helpful if this new prop is included in the docs under the [Intercom provider section](https://github.com/amarnath-cohesive/react-live-chat-loader/blob/9f52ea466ea2d5508b93336ef71b0fc3904420f8/README.md?plain=1#L199).

2023-10-12 23:33 UTC, robmorieson commented on src/types.ts
> +import { CSSProperties } from 'react'
This import isn't necessary — it currently throws a warning when running `npm run build`

2023-10-12 23:33 UTC, robmorieson commented on src/components/Intercom/index.tsx
> +        ...wrapperStyleProps
In testing this I wasn't able to affect the position of the placeholder icon with the styles on the container.  

If I moved `...wrapperStyleProps` down to the `div` with `role="button"` below it worked.   Perhaps the styles would make more sense there?

2024-01-09 00:44 UTC, benschwarz commented
Hey @amarnath-cohesive, seeing as there's no response here and work still required we'll take it that you've moved on to other things. If not, let me know and we'll re-discuss in the future. Thanks!

2024-01-09 00:44 UTC, closed without merging