Added userlike provider
calibreapp/react-live-chat-loader pull request #43
Opened 2020-12-31 03:13 UTC by gazpachu

I've installed the package like this: `npm install --save ../react-live-chat-loader` (no errors)

Then imported it with `import { LiveChatLoaderProvider, Userlike } from 'react-live-chat-loader'`

Added the Provider with `<LiveChatLoaderProvider providerKey="xxxx" provider="userlike">

And called the widget with `<Userlike />`

I get this error trying to test it on my Next.js website:

<img width="747" alt="Screenshot 2020-12-31 at 12 11 29" src="https://user-images.githubusercontent.com/1721288/103392459-5e3e8a80-4b61-11eb-8a46-a5a34cf7483f.png">

2021-01-03 22:11 UTC, mikedijkstra commented
Hi @gazpachu,

We recommend that you install the package from npm rather than referencing it locally (e.g. `npm install react-live-chat-loader`).

When you reference it locally you need to link React so it uses the same version of React. You can find out more [here in the React documentation](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react).

Also, I believe this would be better as an [Issue](https://github.com/calibreapp/react-live-chat-loader/issues) rather than a Pull Request so I'm going to close this for now.

Please open a new issue if the above doesn't solve your problem.

Thanks!

2021-01-03 22:42 UTC, mikedijkstra commented
Hi @gazpachu,

I've just had another look at this and can see you're in the process of adding a new integration.

To test locally you'll need to link React with so you're using the same React in your Next.JS website and the live chat loader. [See this link for more information](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react).

2021-01-21 23:31 UTC, benschwarz commented
Hey @gazpachu, just wanted to see if there's anything we can to do help finalise this?

2021-01-22 03:13 UTC, gazpachu commented
Hi @benschwarz, I've been quite busy at work. Will try to finish it this weekend

2021-01-23 09:12 UTC, gazpachu commented
> you'll need to link React
I'm not sure how to do that link. I've tried using the same react version on both package.json but it didn't fix it.

2021-01-23 10:30 UTC, gazpachu commented
Ok, ready to review

2021-01-25 01:02 UTC, mikedijkstra requested changes
Thanks for the PR @gazpachu!

After testing it out I've made a few suggestions for improvements and spotted one bug.

I also noticed in the Userlike UI that there are some additional configuration options, such as:

- Button position
- Button offset
- Button style (square or round)
- Button profile desktop
- Button profile mobile

I think it'd be good to include these, is this something you're happy to add to this PR? I imagine the button position would be like the `horizontalPosition` prop on the `HelpScout` widget and the others we could add as additional props to the `Userlike` component.

2021-01-30 01:03 UTC, gazpachu commented on src/components/Userlike/index.js
> +          color,
I was using `fill="currentColor"`, but yeah, we can apply the color directly to the SVG instead

2021-01-30 01:44 UTC, gazpachu commented
Thanks for the review!

2021-01-30 10:41 UTC, gazpachu commented
Regarding these two options:

- Button profile desktop
- Button profile mobile

I think from the plugin perspective, we only need to know if the fake button needs to be shown or not, on either desktop or mobile. For that case, I'd prefer to leave that logic outside this plugin.

2021-02-01 03:25 UTC, mikedijkstra commented
> I think from the plugin perspective, we only need to know if the fake button needs to be shown or not, on either desktop or mobile. For that case, I'd prefer to leave that logic outside this plugin.

Okay, I'm happy to leave that out too then.

I think the last thing is make the `provider.open()` call work. Because `userlike` isn't immediately available we have the same problem as before. The idea behind this function is that if a user clicks on the faux chat widget then we open it up after we've loaded the real chat widget. Right now `userlike` isn't available so it's not loading. Do you think we could do another attempt loop to open it when available?

2021-02-13 07:54 UTC, gazpachu commented
Now it works 👍

2021-02-17 04:30 UTC, benschwarz commented
Hey @gazpachu, just wanted to let you know that @mikedijkstra is on leave so there will be some delay in finalising this PR.

Again, just wanted to re-iterate: Thanks for working on the Userlike provider!

2021-03-19 02:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calibreapp/react-live-chat-loader?pullRequest=43) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calibreapp/react-live-chat-loader?pullRequest=43) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calibreapp/react-live-chat-loader?pullRequest=43) it.</sub>

2021-03-28 22:56 UTC, mikedijkstra approved these changes

2021-03-28 23:08 UTC, mikedijkstra commented
@gazpachu I'm back! Thanks for your patience. The changes look good. Once you sign the CLA we can merge this in and push out a new release 🎉

2021-03-29 00:53 UTC, gazpachu commented
> Once you sign the CLA
Done

2021-03-29 22:18 UTC, merged

2021-03-29 22:26 UTC, mikedijkstra commented
@all-contributors please add @gazpachu for code