Allow using a custom icon for Intercom
calibreapp/react-live-chat-loader pull request #467
Opened 2024-12-15 23:43 UTC by leviceccato

This PR adds support for defining a custom icon for the Intercom widget. It only allows you to override the initial icon in the same way the Intercom UI does.

## Related issues

https://github.com/calibreapp/react-live-chat-loader/issues/241

## Screenshots

Example of using a custom Icon:

![image](https://github.com/user-attachments/assets/c53cea61-a753-4902-a692-5a1bc8dac0d1)

2024-12-15 23:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calibreapp/react-live-chat-loader?pullRequest=467) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calibreapp/react-live-chat-loader?pullRequest=467) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calibreapp/react-live-chat-loader?pullRequest=467) it.</sub>

2024-12-16 00:40 UTC, benschwarz commented
Thanks for your contribution @leviceccato 🤗 

Would you be able to update the readme usage documentation for the intercom provider? It will be helpful to have the option documented so people know it exists 🙇‍♂️

2024-12-16 02:17 UTC, benschwarz requested changes
LGTM. Let’s update the documentation to finalise, then I can handle merge & release.

2024-12-16 02:52 UTC, leviceccato commented
@benschwarz Thanks @benschwarz ! Have just documented.

2024-12-23 05:18 UTC, Harry-Ross approved these changes

2025-01-03 03:39 UTC, merged

2025-01-03 03:39 UTC, benschwarz commented
Thanks again @leviceccato 🙇‍♂️